image: archlinux
packages:
  - arduino-cli
  - python3
  - make
  - git
tasks:
  - libraries: |
      arduino-cli --additional-urls=https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json core update-index
      # Install the core for rp2040
      arduino-cli --additional-urls=https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json core install rp2040:rp2040
      arduino-cli lib install "MIDI library" "Adafruit NeoPixel" "U8g2" "Adafruit GFX Library" "GEM"
      sed -i 's@#include "config/enable-glcd.h"@//\0@g' ~/Arduino/libraries/GEM/src/config.h # remove dependency from GEM
  - build: |
      cd Hex*
      make
      mv build/build.ino.uf2 ../hexboard.ino.uf2
      sha256sum ../hexboard.ino.uf2
artifacts:
  - hexboard.ino.uf2
